name: Criar EC2 com Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform
        run: terraform init

      - name: Verificar Terraform Plan
        run: terraform plan

      - name: Aplicar Terraform (Criar EC2)
        run: terraform apply -auto-approve

      - name: Exibir detalhes da instância
        run: aws ec2 describe-instances --filters "Name=tag:Name,Values=MinhaMaquinaDeTeste" --query "Reservations[].Instances[].InstanceId"

      # - name: Apagar instância (Limpeza)
      #   run: terraform destroy -auto-approve
